### PR TITLE
don't use requirements or git for testing and running, also adapt readme

### PR DESCRIPTION
**Pull request by hpk42**
also contains a str/bytes fix for py35 and an extended README (which i thought we had already merged but anyways).

### CODE REVIEW

**Comment by bogdan-kulynych** [comment]
Thanks a lot!
Do you know why the rendering of README broke on Github?

**Comment by azul** [comment]
hi @bogdan-kulynych 
I can look into it.

**Comment by bogdan-kulynych** [comment]
The string handling changes broke Python 2.7: https://travis-ci.org/claimchain/claimchain-core/jobs/382584072

**Comment by azul** [comment]
@bogdan-kulynych fixed the readme. Heading markers were inconsistent.
The failing py 2.7 test is strange. Github showed me a green checkmark.

Will investigate.

**Pull request merged**
